import "./globals.scss";
import { inter, poppins, outfit } from "./fonts";

export const metadata = {
  title: "Deployment Hero",
  description: "Generated by Next.js, TypeScript, SCSS, and Tailwind CSS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable} ${poppins.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
